# Generated by Django 5.2.10 on 2026-01-29 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HireMe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ImageField(upload_to='volunteer_pic')),
                ('description', models.TextField()),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('others', 'others')], max_length=10)),
                ('contact', models.CharField(max_length=10)),
                ('service_type', models.CharField(choices=[('walk', 'Walk'), ('sit', 'Sit'), ('feed', 'Feed'), ('gromming', 'gromming'), ('training', 'training')], max_length=20)),
                ('service_charge', models.DecimalField(decimal_places=2, max_digits=8)),
                ('date', models.DateTimeField()),
                ('available_from', models.DateTimeField()),
                ('available_to', models.DateTimeField()),
            ],
        ),
    ]
