# Generated by Django 5.2.10 on 2026-01-31 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hire', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hireme',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
