# Generated by Django 5.1.7 on 2026-02-24 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genericapp', '0001_initial'),
        ('job', '0008_myjobpost_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Applications',
            new_name='ProviderApplication',
        ),
        migrations.CreateModel(
            name='CustomerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hire_requests_sent', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hire_requests_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('customer', 'provider')},
            },
        ),
    ]
