# Generated by Django 5.2.10 on 2026-02-05 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_client_id_alter_clientkyc_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='role',
        ),
        migrations.AddField(
            model_name='client',
            name='roles',
            field=models.JSONField(default=list),
        ),
    ]
