# Generated by Django 5.2.10 on 2026-02-05 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_client_role_client_roles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='roles',
            new_name='role',
        ),
    ]
