# Generated by Django 5.2.10 on 2026-02-10 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_roles_client_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientkyc',
            name='contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='clientkyc',
            name='pincode',
            field=models.CharField(default=7987725298, max_length=10),
            preserve_default=False,
        ),
    ]
