# Generated by Django 5.2.10 on 2026-02-09 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_roles_client_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientkyc',
            name='contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
