# Generated by Django 5.2.10 on 2026-02-13 08:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_clientkyc_contact_alter_clientkyc_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientkyc',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userkyc', to=settings.AUTH_USER_MODEL),
        ),
    ]
