# Generated by Django 5.2.10 on 2026-02-13 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_clientkyc_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='has_susbscription',
            new_name='has_subscription',
        ),
    ]
