# Generated by Django 5.2.10 on 2026-01-31 05:37

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PetBreed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PetType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_type', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='jobpost',
            old_name='date',
            new_name='job_date',
        ),
        migrations.RenameField(
            model_name='jobpost',
            old_name='description',
            new_name='job_description',
        ),
        migrations.RenameField(
            model_name='jobpost',
            old_name='title',
            new_name='job_title',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='job_type',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='pet_breed',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='pet_type',
        ),
        migrations.AddField(
            model_name='jobpost',
            name='job_service',
            field=models.CharField(choices=[('walking', 'walking'), ('grooming', 'grooming'), ('sitting', 'sitting'), ('training', 'training')], default=0, max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='job_days',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)]),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='job_duration',
            field=models.DecimalField(decimal_places=2, help_text='Duration in hours', max_digits=4),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('assigned', 'Assigned'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=20),
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.PositiveIntegerField()),
                ('difficulty', models.CharField(blank=True, max_length=20, null=True)),
                ('is_mixed', models.BooleanField(default=False)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pets', to=settings.AUTH_USER_MODEL)),
                ('breeds', models.ManyToManyField(blank=True, to='job.petbreed')),
                ('pet_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='job.pettype')),
            ],
        ),
        migrations.AddField(
            model_name='jobpost',
            name='pet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='job.pet'),
        ),
        migrations.AddField(
            model_name='petbreed',
            name='pet_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='breeds', to='job.pettype'),
        ),
        migrations.AlterUniqueTogether(
            name='petbreed',
            unique_together={('pet_type', 'breed_name')},
        ),
    ]
