# Generated by Django 5.2.10 on 2026-02-07 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_alter_jobpost_id_alter_pet_id_alter_petbreed_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='breeds',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='pet_type',
        ),
        migrations.CreateModel(
            name='PetJobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_profile', models.ImageField(upload_to='pet_profile')),
                ('pet_name', models.CharField(max_length=30)),
                ('age', models.DecimalField(decimal_places=1, max_digits=3)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=4)),
                ('gender', models.CharField(max_length=20)),
                ('job_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('duration', models.TimeField()),
                ('service_type', models.CharField(choices=[('walking', 'walking'), ('grooming', 'grooming'), ('sitting', 'sitting'), ('training', 'training')], max_length=30)),
                ('difficulty', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=300)),
                ('is_vaccinated', models.BooleanField(default=False)),
                ('is_mixed_breed', models.BooleanField(default=False)),
                ('pet_breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.petbreed')),
                ('pet_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.pettype')),
            ],
        ),
        migrations.DeleteModel(
            name='JobPost',
        ),
        migrations.DeleteModel(
            name='Pet',
        ),
    ]
