# Generated by Django 5.2.10 on 2026-02-07 20:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_remove_pet_breeds_remove_pet_owner_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MyJobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_profile', models.ImageField(upload_to='pet_profile')),
                ('pet_name', models.CharField(max_length=30)),
                ('age', models.DecimalField(decimal_places=1, max_digits=3)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=4)),
                ('gender', models.CharField(max_length=20)),
                ('job_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('service_type', models.CharField(choices=[('walking', 'walking'), ('grooming', 'grooming'), ('sitting', 'sitting'), ('training', 'training')], max_length=30)),
                ('difficulty', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=300)),
                ('is_vaccinated', models.BooleanField(default=False)),
                ('is_mixed_breed', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pet_breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.petbreed')),
                ('pet_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.pettype')),
            ],
        ),
        migrations.DeleteModel(
            name='PetJobPost',
        ),
    ]
