# Generated by Django 5.2.10 on 2026-02-12 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_myjobpost_delete_petjobpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myjobpost',
            name='service_type',
            field=models.CharField(choices=[('walker', 'walker'), ('groomer', 'groomer'), ('sitter', 'sitter'), ('care', 'care')], max_length=30),
        ),
    ]
