# Generated by Django 5.2.10 on 2026-02-18 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_alter_myjobpost_service_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='myjobpost',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
