# Generated by Django 5.2.10 on 2026-02-10 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribeduserplan',
            name='end_date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='subscribeduserplan',
            name='start_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
