# Generated by Django 5.2.10 on 2026-02-11 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_providerservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerservice',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='providerservice',
            name='service',
            field=models.CharField(choices=[('walker', 'walker'), ('sitter', 'sitter'), ('groomer', 'groomer'), ('care', 'care/trainer')], max_length=20, unique=True),
        ),
    ]
