# Generated by Django 5.2.10 on 2026-02-13 08:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0005_alter_providerservice_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribeduserplan',
            name='subscription_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subs_plan', to='subscription.subscriptionplan'),
        ),
        migrations.AlterField(
            model_name='subscribeduserplan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subs_user_plan', to=settings.AUTH_USER_MODEL),
        ),
    ]
