# Generated by Django 5.2.10 on 2026-02-19 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0006_alter_subscribeduserplan_subscription_plan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerservice',
            name='service',
            field=models.CharField(choices=[('walker', 'walker'), ('sitter', 'sitter'), ('groomer', 'groomer'), ('care', 'care/trainer')], max_length=20),
        ),
    ]
