# Generated by Django 5.1.7 on 2026-02-23 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0007_alter_providerservice_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='currency',
        ),
    ]
